---
kind: Namespace
apiVersion: v1
metadata:
  name: tdpd13
  labels:
    name: odoo
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-db
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  ports:
    - port: 5432
  selector:
    app: odoo-shop
    tier: backend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-db
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-shop
      tier: backend
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: backend
    spec:
      containers:
        - image: postgres:10.0
          name: odoo-db
          env:
            - name: POSTGRES_USER
              value: odoo
            - name: POSTGRES_PASSWORD
              value: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: odoo-db
          volumeMounts:
            - name: odoo-db-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: odoo-db-pvc
          persistentVolumeClaim:
            claimName: odoo-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-shop
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  ports:
    - port: 8069
  selector:
    app: odoo-shop
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: odoo-shop
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: odoo-shop
      tier: frontend
  template:
    metadata:
      labels:
        app: odoo-shop
        tier: frontend
    spec:
      containers:
        - image: odoo:13.0
          name: odoo-shop
          env:
            - name: USER
              value: odoo
            - name: PASSWORD
              value: password
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - containerPort: 8069
              name: odoo
          volumeMounts:
            - name: odoo-pvc
              mountPath: /var/lib/odoo
      volumes:
        - name: odoo-pvc
          persistentVolumeClaim:
            claimName: odoo-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/pv0003/
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0004
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/pv0004/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-pvc
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: odoo-db-pvc
  namespace: tdpd13
  labels:
    app: odoo-shop
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
